name: test_workflow_1

on: push

jobs: 
    explore-github-actions:
        runs-on: ubuntu-latest
        steps:
            - name: Greet Msg
              run: echo "First Workflow!!!"

            - name: Checkout Repo
              uses: actions/checkout@v4

            # - name: Listing Files
            #   run: ls -la
            
            # - name: Reading Content
            #   run: cat .github/workflows/test_workflow_1.yml

            - name : Multiline Script
              run: |
                ls -la
                cat .github/workflows/test_workflow_1.yml

            - name: Script Run from Repo Root
              run: |
                chmod +x ./test_script.sh
                ./test_script.sh