name: test_workflow_1

on: push

env:
  WORKFLOW_MESSAGE: This is a workflow level env

jobs: 
    explore-github-actions:
        env:
          JOB_MESSAGE: "This is a job level env"
        runs-on: ubuntu-latest
        steps:
            - name: Greet Msg
              env:
                MESSAGE: "First Workflow"
              run: |
                echo "${{ env.MESSAGE }}!!!"  #env at step level
                echo ${{ env.JOB_MESSAGE }}

            - name: Checkout Repo
              uses: actions/checkout@v4

            # - name: Listing Files
            #   run: ls -la
            
            # - name: Reading Content
            #   run: cat .github/workflows/test_workflow_1.yml

            - name : Multiline Script
              run: |
                ls -la
                cat .github/workflows/test_workflow_1.yml
                echo ${{ env.JOB_MESSAGE }}

            - name: Script Run from Repo Root
              run: |
                chmod +x ./test_script.sh
                ./test_script.sh
            
            - name: upload artifact file
              uses: actions/upload-artifact@v4
              with:
                name: out-file
                path: out.txt
    
    another-job:
        needs: explore-github-actions
        runs-on: ubuntu-latest
        steps:
            - name: download artifact file
              uses: actions/download-artifact@v4
              with:
                name: out-file

            - name: Read Contents
              run: cat out.txt
            
            - name: Print Workflow level env
              run: echo ${{ env.WORKFLOW_MESSAGE }}

            - name: Print Repository level Variable and Secret
              run: echo ${{ secrets.TEST_REPOSITORY_SECRET }} and ${{ vars.TEST_REPOSITORY_VARIABLE }}