name: test_workflow_1

on: push

jobs: 
    explore-github-actions:
        runs-on: ubuntu-latest
        steps:
            - run: echo "First Workflow!!!"
            - run: echo "Testing push events"
            - run: echo "test4"